name: Manual Unzip reviactyl.zip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip reviactyl.zip
        run: |
          unzip -o reviactyl.zip -d temp_unzip
          cp -r temp_unzip/* .
          rm -rf temp_unzip
          rm reviactyl.zip

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped and moved files from reviactyl.zip to root" || echo "No changes to commit"
          git push
